name: Azure Container Apps Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v3

            - name: Log in to Azure
              uses: azure/login@v3
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            
            - name: Build and Deploy Container App
              uses: azure/container-apps-deploy-aztion@v1
              with:
                appSourcePath: ${{ github.workspace }}/src
                acrName: cae8787cdd5cacr
                containerAppName: my-container-app
                resourceGroup: yuvarajsonale1991_rg_6472
